### ISSUE TITLE
Feature Request: Make compatible with Android Oreo 8.0

### ISSUE THREAD

**Issue by timrijckaert** [friendlyrobotnyc/TinyDancer#61]
Hi 
According to [Android 8.0 Behavior Changes](https://developer.android.com/about/versions/oreo/android-8.0-changes.html#all-aw) apps that target API 26 should now be using the [TYPE_APPLICATION_OVERLAY](https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#TYPE_APPLICATION_OVERLAY) instead of the [SYSTEM_ALERT_WINDOW](https://developer.android.com/reference/android/Manifest.permission.html#SYSTEM_ALERT_WINDOW).

If not you get this nice stacktrace.

`Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@c3386fe -- permission denied for window type 2002
                                                                                          at android.view.ViewRootImpl.setView(ViewRootImpl.java:789)
                                                                                          at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
                                                                                          at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
                                                                                          at com.codemonkeylabs.fpslibrary.ui.TinyCoach.addViewToWindow(TinyCoach.java:80)
                                                                                          at com.codemonkeylabs.fpslibrary.ui.TinyCoach.<init>(TinyCoach.java:52)
                                                                                          at com.codemonkeylabs.fpslibrary.TinyDancerBuilder.show(TinyDancerBuilder.java:94)
                                                                                          at com.foo.bar.MyApplication.initTinyDancer(MyApplication.kt:128)
                                                                                          at com.foo.bar.MyApplication.onCreate(MyApplication.kt:76)
                                                                                          at com.zeroturnaround.jrebel.android.agent.runtime.client.JRebelApplication.onCreate(SourceFile:139)
                                                                                          at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118) 
                                                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791) 
                                                                                          at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                          at android.os.Looper.loop(Looper.java:164) 
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                                          at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) `

Thanks in advance.

Tim

**Comment by brianPlummer** [comment]
thanks @timrijckaert !! it's fixed!
